<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>13</LangVersion>
    <Configurations>Debug;Release;Release_Internal;Debug_Internal</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\E.Standard.Cms.Configuration\E.Standard.Cms.Configuration.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibGit2Sharp" Version="0.32.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="E.Standard.Cms.Git.Tests" />
  </ItemGroup>

</Project>
